---
project_name: stiletto

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm
          - arm64

release:
    prerelease: auto

archives:
    - wrap_in_directory: true

      format_overrides:
          - goos: windows
            format: zip
checksum:
    name_template: checksums.txt

snapshot:
    name_template: '{{ .Tag }}-next'

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^*.md:'
