---
name: Generate New Version

on:
    push:
        branches:
            - main
            - master
            - production
        paths-ignore:
            - TaskFile.yml
            - CHANGELOG.md

defaults:
    run:
        shell: bash

jobs:

    generate-version:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: '0'

            - name: Generate tag & bump version
              uses: anothrNick/github-tag-action@1.61.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
